name: test-integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        working-directory: ./containerization/
        run: docker-compose up -d && sleep 30
      - name:  Testing
        run: docker ps -a
      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: run and install test-directory
        working-directory: ./test
        run: npm install newman
      - name: test
        working-directory: ./test
        run: npm test
